# Generated by Django 5.0.12 on 2025-04-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_alter_file_table'),
        ('task_assignment', '0002_alter_taskassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang thực hiện'), ('REVIEW', 'Đang xem xét'), ('DONE', 'Hoàn thành')], default='IN_PROGRESS', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_detail', to='file.file', verbose_name='file')),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_file', to='task_assignment.taskassignment', verbose_name='Công việc được giao')),
            ],
            options={
                'verbose_name': 'chi tiết file',
                'verbose_name_plural': 'Các chi tiết file',
                'db_table': 'file_details',
            },
        ),
    ]
