# Generated by Django 5.0.12 on 2025-04-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
    ]
