# Generated by Django 5.0.12 on 2025-04-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Các tài liệu'},
        ),
    ]
