# Generated by Django 5.0.12 on 2025-04-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='link',
            new_name='link_file',
        ),
    ]
