# Generated by Django 5.0.12 on 2025-04-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_rename_link_file_link_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='link_file',
            new_name='link',
        ),
    ]
