# Generated by Django 5.0.12 on 2025-04-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatroom', '0001_initial'),
        ('employee', '0003_alter_employee_position'),
        ('file', '0003_alter_file_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatroom.chatroom')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='file.file')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Các tin nhắn',
                'db_table': 'messages',
            },
        ),
    ]
