# Generated by Django 5.0.12 on 2025-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('role_id', models.IntegerField(verbose_name='Mã nhóm quyền')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Tên tài khoản')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Các tài khoản',
                'db_table': 'accounts',
                'ordering': ['username'],
            },
        ),
    ]
