# Generated by Django 5.0.12 on 2025-03-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Các tài khoản'},
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
