# Generated by Django 5.0.12 on 2025-03-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_managers_remove_account_username_and_more'),
        ('employee', '0002_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to='employee.employee'),
        ),
    ]
