# Generated by Django 5.0.12 on 2025-03-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('project_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parts', to='project.project', verbose_name='Dự án'),
        ),
    ]
