# Generated by Django 5.0.12 on 2025-03-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_options_alter_department_table'),
        ('project', '0001_initial'),
        ('project_part', '0002_alter_projectpart_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpart',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_parts', to='department.department'),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parts', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
