# Generated by Django 5.0.12 on 2025-03-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('task', '0003_alter_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESPONSIBLE', 'Người chịu trách nhiệm'), ('DOER', 'Người làm')], max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang thực hiện'), ('REVIEW', 'Đang xem xét'), ('DONE', 'Hoàn thành')], default='IN_PROGRESS', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='employee.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='task.task')),
            ],
        ),
    ]
