# Generated by Django 5.0.12 on 2025-03-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_departmentid'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeID',
        ),
        migrations.AlterField(
            model_name='employee',
            name='departmentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='Mã phòng ban'),
        ),
    ]
