# Generated by Django 5.0.12 on 2025-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('TP', 'Trưởng phòng'), ('NV', 'Nhân viên'), ('TN', 'Trưởng nhóm'), ('PP', 'Phó phòng')], max_length=2),
        ),
    ]
