# Generated by Django 5.0.12 on 2025-03-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_departmentid'),
        ('employee', '0002_remove_employee_employeeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departmentID',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='Mã phòng ban'),
            preserve_default=False,
        ),
    ]
