# Generated by Django 5.0.12 on 2025-03-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_departmentid_employee_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
