# Generated by Django 5.0.12 on 2025-03-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_managerid'),
        ('employee', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employees', to='department.department', verbose_name='Mã phòng ban'),
        ),
    ]
