# Generated by Django 5.0.12 on 2025-03-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0003_alter_department_options_alter_department_table'),
        ('task', '0003_alter_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='department.department', verbose_name='Phòng ban')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tasks', to='task.task', verbose_name='Công việc')),
            ],
            options={
                'verbose_name': 'Công việc phòng ban',
                'verbose_name_plural': 'Các công việc phòng ban',
                'db_table': 'department_tasks',
            },
        ),
    ]
