# Generated by Django 5.0.12 on 2025-03-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_alter_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('history_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã lịch sử công việc')),
                ('updated_date', models.DateTimeField(verbose_name='Ngày cập nhật')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='task.task', verbose_name='Mã công việc')),
            ],
            options={
                'verbose_name': 'Lịch sử công việc',
                'verbose_name_plural': 'Các lịch sử công việc',
                'db_table': 'work_histories',
            },
        ),
    ]
