# Generated by Django 5.0.12 on 2025-03-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('role', '0002_alter_role_options_alter_role_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Hành động')),
                ('featureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.feature', verbose_name='Chức năng')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role', verbose_name='Nhóm quyền')),
            ],
            options={
                'verbose_name': 'Chi tiết quyền',
                'verbose_name_plural': 'Các chi tiết quyền',
                'db_table': 'role_detail',
            },
        ),
    ]
