# Generated by Django 5.0.12 on 2025-03-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm quyền')),
                ('status', models.BooleanField(default=False, verbose_name='Đã xóa')),
            ],
            options={
                'verbose_name': 'Nhóm quyền',
                'verbose_name_plural': 'Các các quyền',
                'db_table': 'roles',
            },
        ),
    ]
