# Generated by Django 5.0.12 on 2025-03-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Quyền', 'verbose_name_plural': 'Các quyền'},
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
