# Generated by Django 5.0.12 on 2025-03-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Nhóm quyền', 'verbose_name_plural': 'Các nhóm quyền'},
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
    ]
