# Generated by Django 5.0.12 on 2025-03-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Chức năng', 'verbose_name_plural': 'Các chức năng'},
        ),
        migrations.AlterModelTable(
            name='feature',
            table='features',
        ),
    ]
