# Generated by Django 5.0.12 on 2025-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Thấp'), (1, 'Trung bình'), (2, 'Cao')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TO_DO', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('ON_HOLD', 'Tạm dừng'), ('DELAYED', 'Trễ hạn'), ('POSTPONED', 'Trì hoãn')], default='TO_DO', max_length=50),
        ),
    ]
