# Generated by Django 5.0.12 on 2025-04-02 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TO_DO', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy'), ('ON_HOLD', 'Tạm dừng'), ('DELAYED', 'Trễ hạn'), ('POSTPONED', 'Trì hoãn')], default='IN_PROGRESS', max_length=50),
        ),
    ]
