# Generated by Django 5.0.12 on 2025-03-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên phần dự án')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Phần dự án',
                'verbose_name_plural': 'Các phần dự án',
                'db_table': 'project_parts',
            },
        ),
    ]
