# Generated by Django 5.0.12 on 2025-03-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0002_alter_feature_options_alter_feature_table'),
        ('role', '0002_alter_role_options_alter_role_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_details', to='feature.feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_details', to='role.role')),
            ],
            options={
                'verbose_name': 'Chi tiết quyền',
                'verbose_name_plural': 'Các chi tiết quyền',
                'db_table': 'role_details',
            },
        ),
    ]
