# Generated by Django 5.0.12 on 2025-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentID', models.IntegerField(verbose_name='Mã phòng ban')),
                ('managerID', models.IntegerField(verbose_name='Mã trưởng phòng')),
                ('departmentName', models.CharField(max_length=255, verbose_name='Tên phòng ban')),
                ('departmentStatus', models.BooleanField(default=False, verbose_name='Trạng thái')),
            ],
        ),
    ]
