# Generated by Django 5.0.12 on 2025-03-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentStatus',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
    ]
