# Generated by Django 5.0.12 on 2025-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_departmentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departmentID',
        ),
    ]
