# Generated by Django 5.0.12 on 2025-03-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Phòng Ban', 'verbose_name_plural': 'Các phòng ban'},
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
