# Generated by Django 5.0.12 on 2025-03-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_departmentid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
