# Generated by Django 5.0.12 on 2025-03-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_table'),
        ('employee', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='managerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_departments', to='employee.employee', verbose_name='Mã trưởng phòng'),
        ),
    ]
