# Generated by Django 5.0.12 on 2025-04-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0004_alter_task_parent_task_alter_task_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='task.task')),
            ],
            options={
                'verbose_name': 'Phòng chat',
                'verbose_name_plural': 'Các phòng chat',
                'db_table': 'chatrooms',
            },
        ),
    ]
